### ISSUE TITLE
Landlord approval and denial of booking request

### ISSUE THREAD

**Issue by AdamSkuse** [rahulrama/arrrgbnb#19]
As a landlord user
So I can maintain control over my space
I would like to be able to approve or deny applications to rent my space

**Comment by naridas** [comment]
heyo adam

**Comment by rahulrama** [comment]
link bookings to the properties and users

**Comment by rahulrama** [comment]
landlord should see pending requests on his dashboard

**Comment by rahulrama** [comment]
landlord should be able to approve or deny requests

**Comment by rahulrama** [comment]
renter's dashboard should be updated with the approval status - dependant or tied in with issues relating to renter's dashboard
