### ISSUE TITLE
Filters for listings

### ISSUE THREAD

**Issue by AdamSkuse** [rahulrama/arrrgbnb#21]
As a rental user
I would like to be able to filter listings by:
booked dates
price
location
sleeps
bedrooms
property type

**Comment by AdamSkuse** [comment]
Update property table - add "booked dates"

**Comment by AdamSkuse** [comment]
update spec with filter

**Comment by AdamSkuse** [comment]
update routes and views

**Comment by danldb** [comment]
Merged without a squirrel?
